# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Available pre-commit hooks
#   https://pre-commit.com/hooks.html
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: check-added-large-files
    -   id: check-json
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: pretty-format-json
        args: [
          '--autofix',
          '--indent', '4',
          '--no-sort-keys',
        ]
    -   id: trailing-whitespace
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        language_version: python3.7
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
# TODO: Enable in the future as we have issues to address.
# -   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
#     sha: v1.0.3
#     hooks:
#     -   id: python-bandit-vulnerability-check
