# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# codecov.io Documentation:
#   https://docs.codecov.io/docs
codecov:
  branch: master
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 0
  round: down
  range: "70...100"

  status:
    project:
      # disable the default status that measures entire project
      default: false
      hub:
        paths:
          # only include coverage in "src/hub" folder
          - src/hub
        enabled: yes
        threshold: 1%
      shared:
        paths:
          # only include coverage in "src/shared" folder
          - src/shared
        enabled: yes
        threshold: 1%
    patch:
      default:
        enabled: yes
        threshold: 1%
    changes: no

  ignore:
    - "docs/*"
    - "node_modules/*"
    - "etc/*"
    - "bin/*"
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
comment:
  layout: "reach, diff, files"
  require_changes: yes
