version: "3.7"

services:
  subhub:
    container_name: subhub
    image: mozilla/subhub
    # The `command` section below can take any command from
    # `doit list` and run them here.
    command: local
    build:
      context: .
      args:
        AWS_ACCESS_KEY_ID: "fake-id"
        AWS_SECRET_ACCESS_KEY: "fake-key"
        STRIPE_API_KEY: "sk_test_123"
        SUPPORT_API_KEY: "support_test"
        LOCAL_FLASK_PORT: 5000
    ports:
      - "5000:5000"