version: "3.7"

services:
  base:
    image: mozilla/subhub-base
    container_name: base
    build:
      context: .
      dockerfile: Dockerfile.base
  sub:
    container_name: sub
    image: mozilla/sub
    command: python3 sub/app.py
    build:
      context: src/sub
      dockerfile: Dockerfile
      args:
        LOCAL_FLASK_PORT: 5000
        DYNALITE_PORT: 4567
    environment:
        AWS_ACCESS_KEY_ID: "fake-id"
        AWS_SECRET_ACCESS_KEY: "fake-key"
        STRIPE_API_KEY: $STRIPE_API_KEY
        SUPPORT_API_KEY: $SUPPORT_API_KEY
        PAYMENT_API_KEY: $PAYMENT_API_KEY
        SUPPORT_API_KEY: $SUPPORT_API_KEY
    ports:
      - "5000:5000"
    depends_on:
      - base
      - dynalite

  hub:
    container_name: hub
    image: mozilla/hub
    command: python3 hub/app.py
    build:
      context: src/hub
      dockerfile: Dockerfile
      args:
        LOCAL_FLASK_PORT: 5001
        DYNALITE_PORT: 4567
    environment:
        AWS_ACCESS_KEY_ID: "fake-id"
        AWS_SECRET_ACCESS_KEY: "fake-key"
        STRIPE_API_KEY: $STRIPE_API_KEY
        HUB_API_KEY: $HUB_API_KEY
    ports:
      - "5001:5001"
    depends_on:
      - base
      - dynalite

  dynalite:
    build: https://github.com/vitarn/docker-dynalite.git
    ports:
      - 4567

  stripe:
    image: stripemock/stripe-mock:latest
    ports:
      - "12111:12111"
      - "12112:12112"
