---
service:
  name: service1

plugins:
  - serverless-python-requirements
  - serverless-plugin-tracing

provider:
  name: aws
  runtime: python3.6
  region: us-west-2

  stage: ${opt:stage, self:custom.defaultStage}
  role: SubhubService1Role
  memorySize: 256
  timeout: 10
  tracing: true
  stackTags:
    service: ${self:service}

package:
  exclude:
    - '**/*'
  include:
    - 'handler.py'
    - 'subhub/**'

custom:
  awsAccountId: 177680776199
  defaultStage: dev
  pythonRequirements:
    dockerizePip: 'non-linux'
    fileName: subhub/requirements.txt
    dockerFile: subhub/Dockerfile
  git-repo: https://github.com/mozilla-it/subhub

functions:
  service1-function1-dev:
    name: subhub-${self:service.name}-function1-${self:provider.stage}
    description: >
      function1 description
    handler: handler.handle
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    environment:
      STAGE: ${self:provider.stage}

resources:
  Resources:
    SubhubService1Role:
      Type: AWS::IAM::Role
      Properties:
        Path: /service/
        RoleName: subhub-service1-${self:provider.stage}-role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: subhub-service1-${self:provider.stage}-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join': [':', ['arn:aws:logs', Ref: 'AWS::Region', Ref: AWS::AccountId, 'log-group:/aws/lambda/*:*:*']]
                - Effect: Allow
                  Action:
                    - kms:Decrypt
                  Resource:
                    - "arn:aws:kms:us-east-1:${self:custom.awsAccountId}:alias/*"
                    - "arn:aws:kms:us-east-1:${self:custom.awsAccountId}:key/*"
                - Effect: Allow
                  Action:
                    - "xray:PutTraceSegments"
                    - "xray:PutTelemetryRecords"
                  Resource:
                    - "*"
