---
service:
  name: missing-fxa-events

plugins:
  - serverless-python-requirements
  - serverless-plugin-tracing
  - serverless-dynamodb-local
  - serverless-offline
provider:
  name: aws
  runtime: python3.7
  region: us-west-2
  stage: ${opt:stage, 'dev'}
  deploymentPrefix: ${self:custom.prefix}
  endpointType: regional
  logRetentionInDays: 90
  memorySize: 128
  timeout: 10
  tracing: true
  snsaccount: ${file(../fxa/accounts.yml):fxa.${self:provider.stage}}
  environment:
    STAGE: ${self:provider.stage}
    DEPLOY_ENV: ${env:DEPLOY_ENV}
    PROJECT_NAME: ${env:PROJECT_NAME}
    BRANCH: ${env:BRANCH}
    REVISION: ${env:REVISION}
    VERSION: ${env:VERSION}
    REMOTE_ORIGIN_URL: ${env:REMOTE_ORIGIN_URL}
    LOG_LEVEL: ${env:LOG_LEVEL}
    PROFILING_ENABLED: ${env:PROFILING_ENABLED}
    DEPLOYED_BY: ${env:DEPLOYED_BY}
    DEPLOYED_WHEN: ${env:DEPLOYED_WHEN}
    USER_TABLE:
      Ref: 'Users'
    EVENT_TABLE:
      Ref: 'Events'
  tags:
    cost-center: 1440
    project-name: subhub
    project-desc: payment subscription REST api for customers
    project-email: subhub@mozilla.com
    deploy-env: ${env:DEPLOY_ENV}
    deploy-method: serverless
    sources: https://github.com/mozilla/subhub
    urls: prod.fxa.mozilla-subhub.app/v1
    keywords: subhub:subscriptions:flask:serverless:swagger
    branch: ${env:BRANCH}
    revision: ${env:REVISION}
    version: ${env:VERSION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'dynamodb:Query'
        - 'dynamodb:Scan'
        - 'dynamodb:GetItem'
        - 'dynamodb:PutItem'
        - 'dynamodb:UpdateItem'
        - 'dynamodb:DeleteItem'
        - 'dynamodb:DescribeTable'
        - 'dynamodb:CreateTable'
      Resource:
        - { 'Fn::GetAtt': ['Users', 'Arn'] }
        - { 'Fn::GetAtt': ['Events', 'Arn'] }
    - Effect: Allow
      Action:
        - 'secretsmanager:GetSecretValue'
      Resource:
        - 'Fn::Join': [':', ['arn:aws:secretsmanager', Ref: AWS::Region, Ref: AWS::AccountId, 'secret:${self:provider.stage}/*']]
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource:
        - 'Fn::Join': [':', ['arn:aws:logs', Ref: AWS::Region, Ref: AWS::AccountId, 'log-group:/aws/lambda/*:*:*']]
    - Effect: Allow
      Action:
        - kms:Decrypt
      Resource:
        - 'Fn::Join': [':', ['arn:aws:kms', Ref: AWS::Region, Ref: AWS::AccountId, 'alias/*']]
        - 'Fn::Join': [':', ['arn:aws:kms', Ref: AWS::Region, Ref: AWS::AccountId, 'key/*']]
    - Effect: Allow
      Action:
        - 'xray:PutTraceSegments'
        - 'xray:PutTelemetryRecords'
      Resource:
        - '*'
    - Effect: Allow
      Action:
        - sns:Publish
      Resource:
        - 'Fn::Join': [':', ['arn:aws:sns', Ref: AWS::Region, Ref: AWS::AccountId, '${self:provider.stage}-fxa-event-data']]
  resourcePolicy: ${self:custom.resourcePolicies.${self:custom.access.${self:provider.stage}}}

package:
  exclude:
    - '**/*'
  include:
    - 'handler.py'
    - 'subhub/**'

custom:
  prefix: ${self:provider.stage}-${self:service.name}
#  subdomain: ${self:provider.stage}.${self:service.name}
  pythonRequirements:
    dockerizePip: 'non-linux'
    fileName: subhub/requirements.txt
  git-repo: https://github.com/mozilla/subhub
  dynamodb:
    start:
      migrate: true
  access:
    prod: restricted
    stage: restricted
    qa: restricted
    dev: unfettered
  resourcePolicies:
    unfettered:
      - Effect: Allow
        Principal: "*"
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*/*/*
    restricted:
      - Effect: Allow
        Principal: "*"
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*/*/version
      - Effect: Allow
        Principal: "*"
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*/*/swagger.json
      - Effect: Allow
        Principal: "*"
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*/*/ui/*
      - Effect: Allow
        Principal: "*"
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*/*/support/*
        Condition:
          IpAddress:
            aws:SourceIp: ${file(../fxa/whitelist.yml):support.${self:provider.stage}}
      - Effect: Allow
        Principal: "*"
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*/*/customer/*
          - execute-api:/*/*/plans
        Condition:
          IpAddress:
            aws:SourceIp: ${file(../fxa/whitelist.yml):payments.${self:provider.stage}}
      - Effect: Allow
        Principal: "*"
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*/*/hub
        Condition:
          IpAddress:
            aws:SourceIp: ${file(../fxa/whitelist.yml):hub}

functions:
  missing-fxa-events:
    name: ${self:custom.prefix}-function
    description: >
      subhub service proccessing missed events
    handler: handler.handle
    events:
      - schedule: rate(6 hours)

resources:
  Resources:
    SubHubSNS:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: FxA ${self:provider.stage} Event Data
        TopicName: ${self:provider.stage}-fxa-event-data
    SubHubTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument:
          Id: AWSAccountTopicAccess
          Version: '2008-10-17'
          Statement:
            - Sid: FxAStageAccess
              Effect: Allow
              Principal:
                AWS: arn:aws:iam::${self:provider.snsaccount}:root
              Action:
                - SNS:Subscribe
                - SNS:Receive
                - SNS:GetTopicAttributes
              Resource: arn:aws:sns:us-west-2:903937621340:${self:provider.stage}-fxa-event-data
        Topics:
          - Ref: SubHubSNS
    Users:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: user_id
            AttributeType: S
        KeySchema:
          -
            AttributeName: user_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
    Events:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: event_id
            AttributeType: S
        KeySchema:
          -
            AttributeName: event_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
