swagger: "2.0"

info:
  title: "SubHub"
  version: "1.0"

consumes:
  - "application/json"
produces:
  - "application/json"

basePath: /v1

paths:
  /stripe-subscription-status:
    get:
      operationId: stripe_calls.subscription_status
      tags:
        - Stripe
      summary: List of Subscriptions
      description: Get list of subscriptions for a premium payments customer
      produces:
        - appliation/json;
      responses:
        200:
          description: Success
        400:
          description: Error missing parameter
      parameters:
        - name: api_token
          in: query
          description: API token
          type: string
          required: True
        - name: fxa
          in: query
          description: FxA ID
          type: string
          required: True
        - name: customer_id
          in: query
          description: Customer ID
          type: string
          required: True

  /stripe-list-plans:
    get:
      operationId: stripe_calls.list_all_plans
      tags:
        - Stripe
      summary: List all Stripe Plans
      description: List all plans available from Stripe
      produces:
        - appliation/json;
      responses:
        200:
          description: Success
        400:
          description: Error missing parameter
      parameters:
        - name: api_token
          in: query
          description: API token
          type: string
          required: True
  /fxa-customer-status:
    get:
      operationId: stripe_calls.fxa_customer_update
      tags:
        - FxA
      summary: Firefox Customer Update
      description: Get updated customer subscription data
      produces:
        - application/json;
      responses:
        200:
          description: Success
        400:
          description: Error missing paremeter
      parameters:
        - name: api_token
          in: query
          description: API Token
          type: string
          required: True
        - name: fxa
          in: query
          description: FxA ID.
          type: string
          required: True
        - name: cust_id
          in: query
          description: Customer ID.
          type: string
          required: True
  /stripe-cancel-subscription:
    post:
      operationId: stripe_calls.cancel_subscription
      tags:
        - Stripe
      summary: Cancel a Subscription
      description: Cancel a Customers Subscription
      produces:
        - application/json;
      responses:
        201:
          description: Subscription cancelation successful
        400:
          description: Error - missing paramenter
      parameters:
        - name: api_token
          in: query
          description: API Token.
          type: string
          required: True
        - name: subscription_id
          in: query
          description: Subscription ID.
          type: string
          required: True
        - name: customer_id
          in: query
          description: Customer ID.
          type: string
          required: True
  /stripe-plan-subscription:
    post:
      operationId: stripe_calls.subscribe_to_plan
      tags:
        - Stripe
      summary: Subscribe to Plan
      description: Subscribe to a Mozilla Plan
      produces:
        - application/json;
      responses:
        201:
          description: Subscription successful
        400:
          description: Error - missing paramenter
      parameters:
        - name: api_token
          in: query
          description: API Token.
          type: string
          required: True
        - name: fxa
          in: query
          description: FxA ID.
          type: string
          required: True
        - name: pmt_token
          in: query
          description: Pay Token.
          type: string
          required: True
        - name: plan_id
          in: query
          description: Plan ID.
          type: string
          required: True
        - name: cust_id
          in: query
          description: Customer ID.
          type: string
          required: True
  /stripe-update-payment-method:
    post:
      operationId: stripe_calls.update_payment_method
      tags:
        - Stripe
      summary: Update Payment Method
      description: Update the credit card on file for a user's account
      produces:
        - application/json
      responses:
        201:
          description: Update successful
        400:
          description: Error - missing parementer
      parameters:
        - name: api_token
          in: query
          description: API Token.
          type: string
          required: True
        - name: fxa
          in: query
          description: FxA ID.
          type: string
          required: True
        - name: pmt_token
          in: query
          description: Pay Token.
          type: string
          required: True
        - name: cust_id
          in: query
          description: Customer ID.
          type: string
          required: True


