Resources:
  Users:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ${self:custom.usersTable}
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      BillingMode: PAY_PER_REQUEST
  DeletedUsers:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ${self:custom.deletedUsersTable}
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      BillingMode: PAY_PER_REQUEST
  Events:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ${self:custom.eventsTable}
      AttributeDefinitions:
        - AttributeName: event_id
          AttributeType: S
      KeySchema:
        - AttributeName: event_id
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      BillingMode: PAY_PER_REQUEST