Resources:
  SubHubSNS:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: FxA ${self:provider.stage} Event Data
      TopicName: ${self:provider.stage}-fxa-event-data
  SubHubTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: AWSAccountTopicAccess
        Version: '2008-10-17'
        Statement:
          - Sid: FxAStageAccess
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::${self:provider.snsaccount}:root
            Action:
              - SNS:Subscribe
              - SNS:Receive
              - SNS:GetTopicAttributes
            Resource: arn:aws:sns:us-west-2:903937621340:${self:provider.stage}-fxa-event-data
      Topics:
        - Ref: SubHubSNS